# Generated by Django 5.1.2 on 2024-12-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject_event', '0002_capturedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturedimage',
            name='source',
            field=models.CharField(choices=[('capture', 'Capture'), ('upload', 'Upload')], default='upload', max_length=50),
        ),
    ]
